### ISSUE TITLE
A couple errors that I can not resolve 🤔 

### ISSUE THREAD

**Issue by jjaimealeman** [dijonmusters/supabase-data-at-the-edge#1]
Thanks for a cool course! I've been looking forward to learning Supabase for a while now, so am looking forward to getting through this.

When I run `npx wrangler dev` I get this error
![wrangler-error](https://i.imgur.com/mTlBrtp.png)

I installed wrangler globally `npm install -g wrangler`

I successfully got it to run earlier by running `wrangler dev --local` but then I got a browser error. I'm near the end of Video Number 3, "Query Supabase from Cloudflare Worker"
![browser-error](https://i.imgur.com/HdeO30o.png)

Also, the comments section at the bottom of the videos does not seem to be working:
![comments-not-working](https://i.imgur.com/PeZZhB4.png)

**Comment by swsalim** [comment]
I'm not sure if it's related but do you have this line?

```
const router = new Router();
```

If yes, try to remove `new`.

```
const router = Router() // no "new", as this is not a real ES6 class/constructor!
```

**Comment by jjaimealeman** [comment]
@swsalim 
Thanks for the reply. I don't remember if I fixed this or not, but have since moved on to learning other topics.
